/* ==========================================================
   EAAS / ATHINA DASHBOARD — script.js
   Single source of truth: athleteData
   All UI values are rendered FROM this object only.
   ========================================================== */

// ---------- ATHLETE DATA OBJECT ----------
// TODO: Replace this static object with real data fetched from
// a database / backend once EAAS backend + database layer exists.
const athleteData = {
  name: "",
  weight: null,
  sleep: null,
  energy: null,
  recovery: null,
  mission: ""
};

// TODO: Quick stats (workouts/streak/records) will also come from
// athleteData or a linked stats object once tracking is built.
const quickStatsData = {
  totalWorkouts: null,
  currentStreak: null,
  personalRecords: null
};

// ---------- 1. DYNAMIC GREETING ----------
function updateGreeting() {
  const hour = new Date().getHours();
  let timeText = "Good Night";

  if (hour >= 5 && hour < 12) timeText = "Good Morning";
  else if (hour >= 12 && hour < 17) timeText = "Good Afternoon";
  else if (hour >= 17 && hour < 21) timeText = "Good Evening";

  document.getElementById("greetingTime").textContent = timeText;

  // TODO: Replace "Welcome Back" with athleteData.name once
  // login / profile system exists (e.g. `Welcome Back, ${athleteData.name}`)
  document.getElementById("greetingSub").textContent = "Welcome Back";
}

// ---------- 2. LIVE DATE & TIME ----------
function updateDateTime() {
  const now = new Date();

  const options = { weekday: 'long', day: 'numeric', month: 'long' };
  const dateStr = now.toLocaleDateString('en-US', options);

  let hours = now.getHours();
  const minutes = now.getMinutes().toString().padStart(2, '0');
  const ampm = hours >= 12 ? 'PM' : 'AM';
  hours = hours % 12 || 12;

  const timeStr = `${hours}:${minutes} ${ampm}`;

  document.getElementById("datetime").textContent = `${dateStr} • ${timeStr}`;
}

// ---------- 3. RENDER RECOVERY CARD FROM athleteData ----------
function renderRecoveryCard() {
  const { recovery, sleep, energy, weight } = athleteData;

  // Recovery % + ring
  if (recovery !== null) {
    setRecoveryRing(recovery);
    document.getElementById("recoveryPercent").textContent = `${recovery}%`;
    document.getElementById("ringLabel").textContent =
      recovery >= 70 ? "READY" : recovery >= 40 ? "CAUTION" : "REST";
  } else {
    setRecoveryRing(0);
    document.getElementById("recoveryPercent").textContent = "--";
    document.getElementById("ringLabel").textContent = "--";
  }

  // Sleep / Energy / Weight
  document.getElementById("sleepValue").textContent = sleep !== null ? `${sleep}h` : "--";
  document.getElementById("energyValue").textContent = energy !== null ? energy : "--";
  document.getElementById("weightValue").textContent = weight !== null ? `${weight}kg` : "--";

  // TODO: These values will eventually come from wearable sync /
  // manual daily check-in feature instead of a static object.
}

function setRecoveryRing(percent) {
  const ring = document.getElementById("ringFill");
  const circumference = 2 * Math.PI * 52; // r = 52
  const offset = circumference - (percent / 100) * circumference;

  ring.style.strokeDasharray = circumference;
  ring.style.strokeDashoffset = offset;
}

// ---------- 4. RENDER MISSION CARD FROM athleteData ----------
function renderMissionCard() {
  const missionText = document.getElementById("missionText");
  const missionTag = document.getElementById("missionTag");

  if (athleteData.mission && athleteData.mission.trim() !== "") {
    missionText.textContent = athleteData.mission;
    missionTag.textContent = "Active";
  } else {
    missionText.textContent = "No mission set yet.";
    missionTag.textContent = "--";
  }

  // TODO: Mission will later be generated by ATHINA's AI Coach
  // based on training plan, recovery score and calendar.
}

// ---------- 5. RENDER QUICK STATS FROM quickStatsData ----------
function renderQuickStats() {
  const { totalWorkouts, currentStreak, personalRecords } = quickStatsData;

  document.getElementById("totalWorkouts").textContent = totalWorkouts ?? "--";
  document.getElementById("currentStreak").textContent = currentStreak ?? "--";
  document.getElementById("personalRecords").textContent = personalRecords ?? "--";

  // TODO: Pull real stats from workout history/database once
  // the Workout Tracker module is built.
}

// ---------- 6. BOTTOM NAV — EMPTY HANDLERS FOR FUTURE PAGES ----------
function goToHome() {
  // TODO: Render Home dashboard (current default view)
  console.log("Navigating to: Home");
}

function goToWorkout() {
  // TODO: Build Workout Tracker page
  console.log("Navigating to: Workout");
}

function goToProgress() {
  // TODO: Build Progress Analytics page (charts, PRs, history)
  console.log("Navigating to: Progress");
}

function goToAthina() {
  // TODO: Build ATHINA Chat / Voice Assistant page (AI API connects here)
  console.log("Navigating to: ATHINA");
}

function goToSettings() {
  // TODO: Build Settings page (profile, preferences, account)
  console.log("Navigating to: Settings");
}

const navHandlers = {
  home: goToHome,
  workout: goToWorkout,
  progress: goToProgress,
  athina: goToAthina,
  settings: goToSettings
};

function setupNavigation() {
  const navItems = document.querySelectorAll(".nav-item");

  navItems.forEach(item => {
    item.addEventListener("click", () => {
      navItems.forEach(i => i.classList.remove("active"));
      item.classList.add("active");

      const section = item.getAttribute("data-nav");
      if (navHandlers[section]) {
        navHandlers[section]();
      }
    });
  });
}

// ---------- 7. START WORKOUT BUTTON ----------
function setupStartButton() {
  const btn = document.getElementById("startWorkoutBtn");
  btn.addEventListener("click", () => {
    // TODO: Start actual workout session flow once Workout module exists.
    console.log("Workout session starting...");
  });
}

// ---------- INIT ----------
function init() {
  updateGreeting();
  updateDateTime();
  renderRecoveryCard();
  renderMissionCard();
  renderQuickStats();
  setupNavigation();
  setupStartButton();

  // Refresh time every 30 seconds
  setInterval(updateDateTime, 30000);
}

document.addEventListener("DOMContentLoaded", init);

// TODO: When database/backend is ready, replace athleteData and
// quickStatsData with an async fetch() call that populates these
// objects before init() renders the UI.